Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2019-09, with the labels that each got.

#114 Add information about navigation subscription buttons
  docs/Displaying a User Interface/Subscribing to System Buttons/index.md
  docs/Video Streaming for Navigation Apps/Introduction/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#129 Sync Message Version
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Other SDL Features/Creating an App Service/index.md
Labels: adding content, platform-iOS

#69 React Native Docs
  config.json
  docs/Frequently Asked Questions/React Native/index.md
Labels: adding content, platform-iOS

#153 Phone Number
  docs/Other SDL Features/Calling a Phone Number/index.md
Labels: fixing content
