Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2019-06, with the labels that each got.

#15 Other / Creating App Services
  docs/Other SDL Features/Creating an App Service/index.md
Labels: platform alignment

#38 Other / Uploading Images
  docs/Other SDL Features/Uploading Images/index.md
Labels: platform alignment

#36 Other / Using App Services
  docs/Other SDL Features/Using App Services/index.md
Labels: platform alignment

#8 Other / Batch Sending RPCs
  docs/Other SDL Features/Batch Sending RPCs/index.md
Labels: platform alignment

#33 Update to Newer SDL
  config.json
  docs/Migrating to Newer SDL Versions/Updating to v4.3+/index.md
  docs/Migrating to Newer SDL Versions/Updating to v4.4/index.md
  docs/Migrating to Newer SDL Versions/Updating to v4.5/assets/invis_notifications.png
  docs/Migrating to Newer SDL Versions/Updating to v4.5/assets/silent_notifications.png
  docs/Migrating to Newer SDL Versions/Updating to v4.5/index.md
  docs/Migrating to Newer SDL Versions/Updating to v4.6/index.md
  docs/Migrating to Newer SDL Versions/Updating to v4.7/index.md
  docs/Migrating to Newer SDL Versions/Updating to v5.0+/index.md
Labels: platform alignment

#19 Other / Getting in car audio
  docs/Other SDL Features/Getting In-Car Microphone Audio/index.md
Labels: platform alignment

#2 Dev Tools / Configuring SDL Logging
  docs/Developer Tools/Configuring SDL Logging/index.md
Labels: platform alignment

#26 Streaming / Intro
  config.json
  docs/Video Streaming for Navigation Apps/Introduction/index.md
Labels: platform alignment

#27 Streaming / Video
  docs/Video Streaming for Navigation Apps/Introduction/index.md
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: platform alignment

#22 Displaying a User Interface / Popup Menus and Keyboards
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/Generic_popup_menu_row.png
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/PerformInteractionIconOnly.png
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/PerformInteractionListOnly.png
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/PerformInteractionListwithSearch.png
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/PerformInteractionManualOnly.png
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/PerformInteractionVROnly.png
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/SYNC3_keyboard_search.jpg
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/SYNC3_popup_menu_row.jpg
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/SYNC3_popup_menu_tiles.jpg
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/SYNC3_popup_menu_voice_recognition.jpg
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/SYNC3_popup_menu_with_search.jpg
  docs/Displaying a User Interface/Popup Menus and Keyboards/index.md
Labels: platform alignment

#28 Streaming / Audio
  docs/Video Streaming for Navigation Apps/Audio Streaming/index.md
Labels: platform alignment

#34 Other SDL Features / Remote Control Vehicle Features
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
Labels: platform alignment

#30 Other SDL Features / Playing Audio Indications
  docs/Other SDL Features/Playing Audio Indications/index.md
Labels: platform alignment

#37 Other SDL Features / Retrieving Vehicle Data
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
Labels: platform alignment

#40 Streaming / Turn By Turn Directions
  docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
Labels: platform alignment

#32 Other SDL Features / Uploading Files
  docs/Other SDL Features/Uploading Files/index.md
Labels: platform alignment

#29 Displaying a User Interface / Main Screen Templates
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_Default_Media.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_double_graphic_with_soft_buttons.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_graphic_with_text.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_graphic_with_text_buttons.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_large_graphic_only.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_large_graphic_with_soft_buttons.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_media_dark.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_non_media.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_text_buttons_only.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_text_buttons_with_graphic.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_text_with_graphic.png
  docs/Displaying a User Interface/Main Screen Templates/assets/GenericHMI/Generic_tiles_only.png
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_Default_Media.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_double_graphic_with_soft_buttons.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_graphic_with_text.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_graphic_with_text_and_soft_buttons.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_graphic_with_text_buttons.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_graphic_with_tiles.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_large_graphic_only.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_large_graphic_with_soft_buttons.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_media.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_non_media.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_text_and_soft_buttons_with_graphic.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_text_buttons_only.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_text_buttons_with_graphic.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_text_with_graphic.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_tiles_only.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_tiles_with_graphic.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_DoubleGraphicSoftButtons.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_GraphicWithText.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_GraphicWithTextAndSoftButtons.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_GraphicWithTextButtons.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_GraphicWithTiles.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_LargeGraphicOnly.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_LargeGraphicWithSoftButtons.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_MediaWithProgressBar.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_MediaWithoutProgressBar.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_NonMediaWithSoftButtons.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_NonMediaWithoutSoftButtons.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_TextAndSoftButtonsWithGraphic.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_TextButtonsOnly.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_TextButtonsWithGraphic.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_TextWithGraphic.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_TilesOnly.png
  docs/Displaying a User Interface/Main Screen Templates/assets/ford_TilesWithGraphic.png
  docs/Displaying a User Interface/Main Screen Templates/assets/generic_LargeGraphicOnly.png
  docs/Displaying a User Interface/Main Screen Templates/assets/generic_LargeGraphicWithSoftButtons.png
  docs/Displaying a User Interface/Main Screen Templates/assets/generic_Media.png
  docs/Displaying a User Interface/Main Screen Templates/assets/generic_NonMedia.png
  docs/Displaying a User Interface/Main Screen Templates/index.md
Labels: adding content, platform alignment

#24 Displaying a User Interface / Media Clock
  docs/Displaying a User Interface/Media Clock/index.md
Labels: platform alignment

#23 Displaying a User Interface / Alerts
  docs/Displaying a User Interface/Alerts/assets/Ford_AlertWithNoSoftButtons.png
  docs/Displaying a User Interface/Alerts/assets/Ford_AlertWithSoftButtons.png
  docs/Displaying a User Interface/Alerts/assets/Generic_alert.png
  docs/Displaying a User Interface/Alerts/assets/SYNC3_alert.jpg
  docs/Displaying a User Interface/Alerts/index.md
Labels: platform alignment

#21 Getting Started / Head Unit Language
  docs/Getting Started/Adapting to the Head Unit Language/index.md
Labels: platform alignment

#17 Displaying a User Interface / Global Voice Commands
  docs/Displaying a User Interface/Global Voice Commands/index.md
Labels: platform alignment

#16 Displaying a User Interface / Main Menu
  docs/Displaying a User Interface/Main Menu/assets/Generic_menu_dark.png
  docs/Displaying a User Interface/Main Menu/assets/SYNC3_menu.jpg
  docs/Displaying a User Interface/Main Menu/assets/ford_MenuAppearance.png
  docs/Displaying a User Interface/Main Menu/assets/generic_MenuAppearance.png
  docs/Displaying a User Interface/Main Menu/index.md
Labels: platform alignment

#14 Displaying a User Interface / Subscribing to System Buttons
  docs/Displaying a User Interface/Subscribing to System Buttons/assets/Generic_template_media_light.png
  docs/Displaying a User Interface/Subscribing to System Buttons/index.md
Labels: platform alignment

#13 Displaying a User Interface / Text, Images, and Buttons
  docs/Displaying a User Interface/Text Images and Buttons/assets/Generic_template_media_dark.png
  docs/Displaying a User Interface/Text Images and Buttons/assets/Generic_template_media_light.png
  docs/Displaying a User Interface/Text Images and Buttons/assets/template-images-dark.png
  docs/Displaying a User Interface/Text Images and Buttons/assets/template-images-light.png
  docs/Displaying a User Interface/Text Images and Buttons/index.md
Labels: platform alignment

#9 Other / Calling a Phone Number
  docs/Other SDL Features/Calling a Phone Number/index.md
Labels: platform alignment

#1 Getting Started / Installation
  docs/Getting Started/Installation/index.md
Labels: platform alignment

#12 Displaying a User Interface / Adaptive Interface Capabilities
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
Labels: platform alignment

#39 Streaming / Touch Input
  config.json
  docs/Video Streaming for Navigation Apps/Touch Input/index.md
Labels: platform alignment

#35 Other SDL Features / Setting the Built-in Navigation Destination
  config.json
  docs/Other SDL Features/Setting the Built-in Nav System Destination/index.md
  docs/Other SDL Features/Setting the Navigation Destination/index.md
Labels: platform alignment

#18 Other / Creating OEM Cloud App Store
  docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
Labels: platform alignment

#25 Getting Started / Permission
  docs/Getting Started/Understanding Permissions/index.md
Labels: platform alignment

#60 Adding Platform specific files to Documentation
  config.json
  docs/Frequently Asked Questions/SDL Notifications/assets/hide_sdl_notification.png
  docs/Frequently Asked Questions/SDL Notifications/assets/sdl_notification.png
  docs/Frequently Asked Questions/SDL Notifications/index.md
  docs/Frequently Asked Questions/Trusted Router Service/index.md
  docs/Getting Started/Deploying to AWS/index.md
  docs/Getting Started/Proguard Guidelines/index.md
  docs/Getting Started/Setting Security Level for Multiplexing/index.md
  docs/Getting Started/Using AOA Protocol/index.md
Labels: platform alignment

#10 Getting Started / SDL Configuration
  docs/Getting Started/SDK Configuration/index.md
Labels: platform alignment

#20 Getting Started / Adding Lock Screen
  config.json
  docs/Getting Started/Adding the Lock Screen/index.md
Labels: platform alignment

#11 Getting Started / Connecting to an Infotainment System
  docs/Getting Started/Connecting to an Infotainment System/index.md
Labels: platform alignment

#31 Streaming / Haptic Feedback
  docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
Labels: platform alignment

#5 Getting Started / Example Apps
  docs/Getting Started/Example Apps/assets/hmi1.png
  docs/Getting Started/Example Apps/assets/hmi2.png
  docs/Getting Started/Example Apps/assets/lockscreen.png
  docs/Getting Started/Example Apps/assets/mainscreen.png
  docs/Getting Started/Example Apps/index.md
Labels: platform alignment

#66 Add Accio as an iOS distribution method
  docs/Getting Started/Installation/index.md
Labels: adding content, platform-iOS

#72 Update the README to include additional information on tags and best practices
  README.md
Labels: adding content

#75 Added a pull request template
  .github/pull_request_template.md
Labels: adding content

#68 iOS and Android June 2019 Content Update
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Main Menu/index.md
  docs/Getting Started/Installation/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Using App Services/index.md
  docs/Video Streaming for Navigation Apps/Audio Streaming/index.md
  docs/Video Streaming for Navigation Apps/Touch Input/index.md
Labels: adding content, epic content update, platform-android, platform-iOS, platform-javaEE, platform-javaSE
