Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2019-10, with the labels that each got.

#132 Alert Icon - Fall 2019 Feature
  docs/Displaying a User Interface/Alerts/assets/Generic_alertIcon.png
  docs/Displaying a User Interface/Alerts/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#133 Template Titles - Fall 2019 Feature
  docs/Displaying a User Interface/Text Images and Buttons/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#107 Add highlight example to soft button documentation
  docs/Displaying a User Interface/Text Images and Buttons/assets/ford_sync3_soft_button_highlight_off.png
  docs/Displaying a User Interface/Text Images and Buttons/assets/ford_sync3_soft_button_highlight_on.png
  docs/Displaying a User Interface/Text Images and Buttons/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#158 Generic Network Signal Data - Fall 2019 Documentation
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#163 Pixel Density and Scale - Fall 2019 Documentation
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: adding content, platform-android, platform-iOS

#172 Clarify that setting custom encoder settings will override head unit settings
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: fixing content, platform-iOS

#141 Main Menu Tiles - Fall Documentation 2019
  docs/Displaying a User Interface/Main Menu/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#143 Dismissible Lock Screen / Disable Lock Screen - Fall 2019 Documentation
  docs/Getting Started/Adding the Lock Screen/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#138 AutoComplete List - Fall Documentation 2019
  docs/Displaying a User Interface/Popup Menus and Keyboards/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#167 Multiple Transports
  config.json
  docs/Getting Started/Multiple Transports/index.md
Labels: fixing content, platform-android, platform-iOS

#136 Remote Control Multiple Modules - Fall 2019 documentation
  docs/Other SDL Features/Remote Control Vehicle Features/assets/Car.png
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#156 Cancel interaction documentation - Fall 2019 documentation
  docs/Displaying a User Interface/Alerts/index.md
  docs/Displaying a User Interface/Popup Menus and Keyboards/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Slider/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#109 Add Preset Button Subscription Examples
  docs/Displaying a User Interface/Subscribing to System Buttons/assets/ford_sync_presetMenu.png
  docs/Displaying a User Interface/Subscribing to System Buttons/assets/ford_sync_presetOptions.png
  docs/Displaying a User Interface/Subscribing to System Buttons/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#174 Update the installation page to use the latest version of the libs
  docs/Getting Started/Installation/index.md
Labels: fixing content, platform-android, platform-iOS, platform-javaSE

#177 Update Accio installation
  docs/Getting Started/Installation/index.md
Labels: fixing content
