Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2019-07, with the labels that each got.

#81 Add Slider Documentation
  config.json
  docs/Displaying a User Interface/Slider/assets/DynamicFooter1.png
  docs/Displaying a User Interface/Slider/assets/DynamicFooter2.png
  docs/Displaying a User Interface/Slider/assets/StaticFooter.png
  docs/Displaying a User Interface/Slider/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#73 Update Alert Docs
  docs/Displaying a User Interface/Alerts/assets/Generic_alert.png
  docs/Displaying a User Interface/Alerts/assets/Generic_alert_buttons.png
  docs/Displaying a User Interface/Alerts/index.md
Labels: fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#92 Android video streaming
  config.json
  docs/Video Streaming for Navigation Apps/Audio Streaming/index.md
  docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
  docs/Video Streaming for Navigation Apps/Introduction/index.md
  docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: platform-android

#84 Feature/migrating android
  config.json
  docs/Migrating to Newer SDL Versions/Updating to v4.9/index.md
Labels: platform-android, platform-javaEE, platform-javaSE

#85 Getting Started Updates
  config.json
  docs/Getting Started/Adapting to the Head Unit Language/index.md
  docs/Getting Started/Adding the Lock Screen/assets/GenericLockScreen_Android.png
  docs/Getting Started/Adding the Lock Screen/index.md
  docs/Getting Started/Connecting to an Infotainment System/assets/hmi1.png
  docs/Getting Started/Connecting to an Infotainment System/assets/hmi2.png
  docs/Getting Started/Connecting to an Infotainment System/assets/manticore1.png
  docs/Getting Started/Connecting to an Infotainment System/index.md
  docs/Getting Started/Example Apps/assets/manticore1.png
  docs/Getting Started/Example Apps/index.md
  docs/Getting Started/Installation/index.md
  docs/Getting Started/Integration Basics/index.md
  docs/Getting Started/Multiple Transports/index.md
  docs/Getting Started/SDK Configuration/index.md
  docs/Getting Started/Setting Security Level for Multiplexing/index.md
  docs/Getting Started/Understanding Permissions/index.md
  docs/Getting Started/Using AOA Protocol/index.md
Labels: adding content, fixing content, platform-android, platform-javaEE, platform-javaSE

#88 Displaying UI Updates
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Alerts/index.md
  docs/Displaying a User Interface/Global Voice Commands/index.md
  docs/Displaying a User Interface/Main Menu/index.md
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Popup Menus and Keyboards/index.md
Labels: adding content, fixing content, platform-android, platform-javaEE, platform-javaSE

#90 Other Features Updates
  docs/Other SDL Features/Batch Sending RPCs/index.md
  docs/Other SDL Features/Calling a Phone Number/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
  docs/Other SDL Features/Getting In-Car Microphone Audio/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Setting the Navigation Destination/index.md
  docs/Other SDL Features/Uploading Files/index.md
  docs/Other SDL Features/Uploading Images/index.md
Labels: adding content, platform-android, platform-javaEE, platform-javaSE

#96 Subscribe to cap when adding a listener
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
Labels: fixing content, platform-android, platform-javaEE, platform-javaSE

#89 Developer Tools Updates
  docs/Developer Tools/Configuring SDL Logging/index.md
Labels: adding content, platform-android, platform-javaEE, platform-javaSE

#77 Update Soft Button Docs
  docs/Displaying a User Interface/Text Images and Buttons/assets/buttonExample.png
  docs/Displaying a User Interface/Text Images and Buttons/index.md
Labels: fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#93 Add iOS Example App Debugging / Help Information
  docs/Getting Started/Example Apps/index.md
Labels: adding content, platform-iOS

#76 Swift 5 Updates
  docs/Developer Tools/Configuring SDL Logging/index.md
  docs/Displaying a User Interface/Global Voice Commands/index.md
  docs/Displaying a User Interface/Main Menu/index.md
  docs/Displaying a User Interface/Popup Menus and Keyboards/index.md
  docs/Displaying a User Interface/Text Images and Buttons/index.md
  docs/Getting Started/Integration Basics/index.md
  docs/Getting Started/Understanding Permissions/index.md
  docs/Other SDL Features/Batch Sending RPCs/index.md
  docs/Other SDL Features/Calling a Phone Number/index.md
  docs/Other SDL Features/Getting In-Car Microphone Audio/index.md
  docs/Other SDL Features/Playing Audio Indications/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Setting the Navigation Destination/index.md
  docs/Other SDL Features/Uploading Files/index.md
  docs/Other SDL Features/Uploading Images/index.md
  docs/Video Streaming for Navigation Apps/Audio Streaming/index.md
  docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
  docs/Video Streaming for Navigation Apps/Introduction/index.md
  docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
  docs/Video Streaming for Navigation Apps/Touch Input/index.md
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: fixing content, platform-iOS

#102 Fix issue in video streaming sample code
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: fixing content, platform-android

#94 removing sync 3 images from images and doc page
  docs/Displaying a User Interface/Alerts/assets/SYNC3_alert.jpg
  docs/Displaying a User Interface/Main Menu/assets/SYNC3_menu.jpg
  docs/Displaying a User Interface/Main Menu/index.md
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_Default_Media.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_double_graphic_with_soft_buttons.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_graphic_with_text.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_graphic_with_text_buttons.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_large_graphic_only.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_large_graphic_with_soft_buttons.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_media.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_non_media.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_text_buttons_only.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_text_buttons_with_graphic.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_text_with_graphic.jpg
  docs/Displaying a User Interface/Main Screen Templates/assets/SYNC3HMI/SYNC3_tiles_only.jpg
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Media Clock/assets/ford_mediaclock.png
  docs/Displaying a User Interface/Media Clock/index.md
  docs/Displaying a User Interface/Popup Menus and Keyboards/assets/SYNC3_popup_menu_row.jpg
  docs/Displaying a User Interface/Popup Menus and Keyboards/index.md
  docs/Other SDL Features/Getting In-Car Microphone Audio/index.md
Labels: fixing content

#83 Added more information about on-screen mirroring to video streaming guide
  docs/Getting Started/Adding the Lock Screen/index.md
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: adding content, fixing content, platform-android, platform-iOS

#86 Added v.6.3+ example for getting app service capability updates
  docs/Other SDL Features/Using App Services/index.md
Labels: adding content, platform-iOS

#78 New Speech and Audio Section
  .gitignore
  config.json
  docs/Speech and Audio/Getting Microphone Audio/assets/Ford_AudioPassThruPrompt.png
  docs/Speech and Audio/Getting Microphone Audio/index.md
  docs/Speech and Audio/Playing Audio Indications/index.md
  docs/Speech and Audio/Playing Spoken Feedback/index.md
  docs/Speech and Audio/Setting Up Voice Commands/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE
