Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2019-11, with the labels that each got.

#165 Encryption - Fall 2019 Documentation
  config.json
  docs/Other SDL Features/Encryption/index.md
  docs/Video Streaming for Navigation Apps/Introduction/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#146 Add guide for Getting the Navigation Destination
  config.json
  docs/Other SDL Features/Getting the Navigation Destination/index.md
  docs/Other SDL Features/Setting the Navigation Destination/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#171 Add GetFile documentation to Using App Services guides
  docs/Other SDL Features/Using App Services/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#178 Fix Accio Documentation Link
  docs/Getting Started/Installation/index.md
Labels: fixing content

#179 Java alignment changes
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Text Images and Buttons/index.md
  docs/Other SDL Features/Uploading Files/index.md
Labels: fixing content, platform-android, platform-javaEE, platform-javaSE

#160 Update guides to reference new SCM properties
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Other SDL Features/Uploading Images/index.md
Labels: fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#130 Fall 2019 release documentation
  config.json
  docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
  docs/Customizing Look and Functionality/Customizing the Keyboard/index.md
  docs/Customizing Look and Functionality/Customizing the Template/assets/template-colors-example.png
  docs/Customizing Look and Functionality/Customizing the Template/index.md
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Alerts/assets/Generic_alertIcon.png
  docs/Displaying a User Interface/Alerts/index.md
  docs/Displaying a User Interface/Main Menu/index.md
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Popup Menus and Keyboards/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Slider/index.md
  docs/Displaying a User Interface/Subscribing to System Buttons/index.md
  docs/Displaying a User Interface/Text Images and Buttons/assets/ford_sync3_soft_button_highlight_off.png
  docs/Displaying a User Interface/Text Images and Buttons/assets/ford_sync3_soft_button_highlight_on.png
  docs/Displaying a User Interface/Text Images and Buttons/index.md
  docs/Getting Started/Adapting to the Head Unit Language/index.md
  docs/Getting Started/Adding the Lock Screen/index.md
  docs/Getting Started/Installation/index.md
  docs/Getting Started/Integration Basics/index.md
  docs/Getting Started/Multiple Transports/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Encryption/index.md
  docs/Other SDL Features/Getting the Navigation Destination/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/assets/Car.png
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Setting the Navigation Destination/index.md
  docs/Other SDL Features/Uploading Files/index.md
  docs/Other SDL Features/Uploading Images/index.md
  docs/Other SDL Features/Using App Services/index.md
  docs/Video Streaming for Navigation Apps/Introduction/index.md
  docs/Video Streaming for Navigation Apps/Menus/index.md
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: epic content update

#184 Fixed broken links
  docs/Displaying a User Interface/Alerts/index.md
  docs/Displaying a User Interface/Main Menu/index.md
Labels: fixing content

#183 Update documentation to use success value instead of resultCode
  docs/Displaying a User Interface/Alerts/index.md
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Slider/index.md
  docs/Other SDL Features/Calling a Phone Number/index.md
  docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Setting the Navigation Destination/index.md
  docs/Speech and Audio/Getting Microphone Audio/index.md
  docs/Speech and Audio/Playing Spoken Feedback/index.md
  docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
Labels: fixing content, platform-iOS
