Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2020-07, with the labels that each got.

#303 Remove duplicate paragraph
  docs/Frequently Asked Questions/React Native/index.md
Labels: fixing content, platform-iOS

#304 updated info for header links
  README.md
Labels: readme

#309 Use updated initializer of `SDLButtonPress`
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Using App Services/index.md
Labels: fixing content, platform-iOS

#308 Update JS Suite guides to use new setRpcNotificationListeners method
  docs/Getting Started/Integration Basics/index.md
  docs/Getting Started/Understanding Permissions/index.md
Labels: adding content, platform-android, platform-javaEE, platform-javaSE, platform-javascript

#311 Update Permissions for iOS 6.7 and Align Code Snippets
  docs/Getting Started/Understanding Permissions/index.md
Labels: fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE, platform-javascript

#307 Update manager callback for language changes
  docs/Getting Started/Adapting to the Head Unit Language/index.md
  docs/Getting Started/Integration Basics/index.md
Labels: fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#315 Add subscribe button manager API
  docs/Displaying a User Interface/Template Subscription Buttons/index.md
  docs/Displaying a User Interface/Template Text/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#317 Update gradle compile lines to use 4.12
  docs/Getting Started/Installation/index.md
Labels: fixing content, platform-android, platform-javaSE

#318 Summer 2020 Documentation Update
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Alerts/index.md
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Media Clock/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Slider/index.md
  docs/Displaying a User Interface/Template Subscription Buttons/index.md
  docs/Displaying a User Interface/Template Text/index.md
  docs/Getting Started/Adapting to the Head Unit Language/index.md
  docs/Getting Started/Adding the Lock Screen/assets/DismissLockScreen_Android.png
  docs/Getting Started/Adding the Lock Screen/assets/GenericLockScreen_Android.png
  docs/Getting Started/Checking Supported Features/index.md
  docs/Getting Started/Installation/index.md
  docs/Getting Started/Integration Basics/index.md
  docs/Getting Started/Understanding Permissions/index.md
  docs/Other SDL Features/Batch Sending RPCs/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
  docs/Other SDL Features/Getting the Navigation Destination/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Setting the Navigation Destination/index.md
  docs/Other SDL Features/Using App Services/index.md
  docs/Speech and Audio/Getting Microphone Audio/index.md
  docs/Speech and Audio/Playing Spoken Feedback/index.md
Labels: adding content, fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE, platform-javascript
