Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2020-05, with the labels that each got.

#248 Added softbutton screenshots
  docs/Displaying a User Interface/Template Custom Buttons/assets/Generic_Image_Only_Soft_Buttons.png
  docs/Displaying a User Interface/Template Custom Buttons/assets/Generic_Text_And_Image_Soft_Buttons.png
  docs/Displaying a User Interface/Template Custom Buttons/assets/Generic_Text_Only_Soft_Buttons.png
  docs/Displaying a User Interface/Template Custom Buttons/assets/Generic_non_media.png
  docs/Displaying a User Interface/Template Custom Buttons/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#253 README update on how to view generated docs for a PR
  README.md
  assets/docs-generated-example.png
Labels: fixing content

#251 Change accio string to a format string
  docs/Getting Started/Installation/index.md
Labels: fixing content, platform-iOS

#268 Update iOS installation guide numbering
  docs/Getting Started/Installation/index.md
Labels: fixing content, platform-iOS

#254 SDK Configuration Additions for JS
  docs/Getting Started/SDK Configuration/index.md
Labels: adding content, platform-javascript

#260 Checking Supported Features Additions for JS
  docs/Getting Started/Checking Supported Features/index.md
Labels: adding content, platform-javascript

#266 Change `as NSNumber` to `NSNumber()`
  docs/Displaying a User Interface/Alerts/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Encryption/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
Labels: fixing content, platform-iOS

#270 Add style guide
  STYLE_GUIDE.md
Labels: adding content

#259 Feature/js infotainment system
  docs/Getting Started/Connecting to an Infotainment System/index.md
Labels: adding content, platform-javascript

#258 Integration Basics Additions for JS
  docs/Getting Started/Integration Basics/index.md
Labels: adding content, platform-javascript

#261 Update Understanding Permissions to have info on the JS Suite
  docs/Getting Started/Understanding Permissions/index.md
Labels: adding content, platform-javascript

#257 Update Head Unit Language for JS Suite
  docs/Getting Started/Adapting to the Head Unit Language/index.md
Labels: adding content, platform-javascript

#256 Add Installation docs for JS Suite
  docs/Getting Started/Installation/index.md
Labels: adding content, platform-javascript

#263 Example Apps Additions for JS
  docs/Getting Started/Example Apps/index.md
Labels: adding content, platform-javascript

#272 Update Customizing Look and Functionality Section for JS Suite
  docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
  docs/Customizing Look and Functionality/Customizing the Keyboard/index.md
  docs/Customizing Look and Functionality/Customizing the Template/index.md
Labels: adding content, platform-javascript

#279 Feature/js speech audio
  docs/Speech and Audio/Getting Microphone Audio/index.md
  docs/Speech and Audio/Playing Audio Indications/index.md
  docs/Speech and Audio/Playing Spoken Feedback/index.md
  docs/Speech and Audio/Setting Up Voice Commands/index.md
Labels: adding content, platform-javascript

#271 JS - Displaying a User Interface
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Alerts/index.md
  docs/Displaying a User Interface/Main Menu/index.md
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Media Clock/index.md
  docs/Displaying a User Interface/Popup Keyboards/index.md
  docs/Displaying a User Interface/Popup Menus/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Slider/index.md
  docs/Displaying a User Interface/Template Custom Buttons/index.md
  docs/Displaying a User Interface/Template Images/index.md
  docs/Displaying a User Interface/Template Subscription Buttons/index.md
  docs/Displaying a User Interface/Template Text/index.md
Labels: adding content, platform-javascript

#286 Remove Configuring SDL Logging for JS Suite Docs
  config.json
Labels: fixing content, platform-javascript

#249 JavaScript Suite Docs
  README.md
  config.json
  docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
  docs/Customizing Look and Functionality/Customizing the Keyboard/index.md
  docs/Customizing Look and Functionality/Customizing the Template/index.md
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Alerts/index.md
  docs/Displaying a User Interface/Main Menu/index.md
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Media Clock/index.md
  docs/Displaying a User Interface/Popup Keyboards/index.md
  docs/Displaying a User Interface/Popup Menus/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Slider/index.md
  docs/Displaying a User Interface/Template Custom Buttons/index.md
  docs/Displaying a User Interface/Template Images/index.md
  docs/Displaying a User Interface/Template Subscription Buttons/index.md
  docs/Displaying a User Interface/Template Text/index.md
  docs/Getting Started/Adapting to the Head Unit Language/index.md
  docs/Getting Started/Checking Supported Features/index.md
  docs/Getting Started/Connecting to an Infotainment System/index.md
  docs/Getting Started/Example Apps/index.md
  docs/Getting Started/Installation/index.md
  docs/Getting Started/Integration Basics/index.md
  docs/Getting Started/SDK Configuration/index.md
  docs/Getting Started/Understanding Permissions/index.md
  docs/Other SDL Features/Batch Sending RPCs/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
  docs/Other SDL Features/Encryption - Not Supported/index.md
  docs/Other SDL Features/Getting the Navigation Destination/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Setting the Navigation Destination/index.md
  docs/Other SDL Features/Uploading Files/index.md
  docs/Other SDL Features/Uploading Images/index.md
  docs/Other SDL Features/Using App Services/index.md
  docs/Speech and Audio/Getting Microphone Audio/index.md
  docs/Speech and Audio/Playing Audio Indications/index.md
  docs/Speech and Audio/Playing Spoken Feedback/index.md
  docs/Speech and Audio/Setting Up Voice Commands/index.md
Labels: adding content, platform-javascript
