Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2020-02, with the labels that each got.

#212 Disable OEM lockscreen logo
  docs/Getting Started/Adding the Lock Screen/index.md
Labels: fixing content

#222 Add information on how to prevent the device from sleeping on iOS
  docs/Video Streaming for Navigation Apps/Introduction/index.md
Labels: adding content, platform-iOS

#214 Adding info for setup encryption manager manually
  docs/Other SDL Features/Encryption/index.md
Labels: adding content

#226 added info on how to disable video background string
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: adding content, platform-iOS
