Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2020-04, with the labels that each got.

#202 Split the large template guide into 3 smaller guides
  config.json
  docs/Displaying a User Interface/Media Clock/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Subscribing to System Buttons/index.md
  docs/Displaying a User Interface/Template Custom Buttons/assets/Generic_non_media.png
  docs/Displaying a User Interface/Template Custom Buttons/assets/ford_sync3_soft_button_highlight_off.png
  docs/Displaying a User Interface/Template Custom Buttons/assets/ford_sync3_soft_button_highlight_on.png
  docs/Displaying a User Interface/Template Custom Buttons/index.md
  docs/Displaying a User Interface/Template Images/assets/Generic_template_media_dark.png
  docs/Displaying a User Interface/Template Images/assets/Generic_template_media_light.png
  docs/Displaying a User Interface/Template Images/index.md
  docs/Displaying a User Interface/Template Subscription Buttons/assets/Generic_template_media_light.png
  docs/Displaying a User Interface/Template Subscription Buttons/assets/ford_sync_presetMenu.png
  docs/Displaying a User Interface/Template Subscription Buttons/assets/ford_sync_presetOptions.png
  docs/Displaying a User Interface/Template Subscription Buttons/index.md
  docs/Displaying a User Interface/Template Text/index.md
  docs/Displaying a User Interface/Text Images and Buttons/assets/buttonExample.png
  docs/Displaying a User Interface/Text Images and Buttons/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Uploading Images/index.md
  docs/Speech and Audio/Setting Up Voice Commands/index.md
  docs/Video Streaming for Navigation Apps/Introduction/index.md
Labels: fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#239 fixed sdlmanager typo in encryption guide
  docs/Other SDL Features/Encryption/index.md
Labels: fixing content, platform-iOS

#240 Added overwrite property to java suite
  docs/Other SDL Features/Uploading Files/index.md
Labels: adding content, platform alignment, platform-android, platform-javaEE, platform-javaSE

#243 Added javeSE and javaEE tags that were missing
  docs/Other SDL Features/Encryption/index.md
Labels: fixing content, platform-javaEE, platform-javaSE

#237 Spring 2020 SCM updates
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
Labels: adding content, platform-android, platform-iOS

#235 Added File Manager Config and added more detail to integration basics page for java suite, Fixed 2 minor IOS issues
  docs/Getting Started/Integration Basics/index.md
Labels: adding content, fixing content, platform alignment, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#238 updated and added new screenshots to lock screen guides
  docs/Getting Started/Adding the Lock Screen/assets/CustomLockScreen.png
  docs/Getting Started/Adding the Lock Screen/assets/CustomLockScreen_Android.png
  docs/Getting Started/Adding the Lock Screen/assets/DismissLockScreen.png
  docs/Getting Started/Adding the Lock Screen/assets/DismissLockScreen_Android.png
  docs/Getting Started/Adding the Lock Screen/assets/GenericLockScreen.png
  docs/Getting Started/Adding the Lock Screen/assets/GenericLockScreen_Android.png
  docs/Getting Started/Adding the Lock Screen/assets/OEMLogoLockScreen.png
  docs/Getting Started/Adding the Lock Screen/assets/OEMLogoLockScreen_Android.png
  docs/Getting Started/Adding the Lock Screen/index.md
Labels: fixing content, platform-android, platform-iOS
