Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2020-10, with the labels that each got.

#322 Add section about seeing NodeJS documentation
  config.json
  docs/NodeJS Documentation/index.md
Labels: adding content, platform-javascript

#333 Add initial subtleAlert docs
  config.json
  docs/Displaying a User Interface/Alerts and Subtle Alerts/assets/Generic_alert.png
  docs/Displaying a User Interface/Alerts and Subtle Alerts/assets/Generic_alertIcon.png
  docs/Displaying a User Interface/Alerts and Subtle Alerts/assets/Generic_alert_buttons.png
  docs/Displaying a User Interface/Alerts and Subtle Alerts/assets/Generic_subtleAlert.png
  docs/Displaying a User Interface/Alerts and Subtle Alerts/assets/Generic_subtleAlertIcon.png
  docs/Displaying a User Interface/Alerts and Subtle Alerts/assets/Generic_subtleAlert_buttons.png
  docs/Displaying a User Interface/Alerts and Subtle Alerts/index.md
  docs/Displaying a User Interface/Alerts/index.md
Labels: adding content

#326 Update Java Suite deprecated code snippets
  docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
  docs/Developer Tools/Configuring SDL Logging/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Slider/index.md
  docs/Displaying a User Interface/Template Custom Buttons/index.md
  docs/Displaying a User Interface/Template Images/index.md
  docs/Displaying a User Interface/Template Text/index.md
  docs/Frequently Asked Questions/Multiple Processes/index.md
  docs/Getting Started/Adapting to the Head Unit Language/index.md
  docs/Getting Started/Checking Supported Features/index.md
  docs/Getting Started/Integration Basics/index.md
  docs/Getting Started/Setting Security Level for Multiplexing/index.md
  docs/Getting Started/Using AOA Protocol/index.md
  docs/Other SDL Features/Calling a Phone Number/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Uploading Files/index.md
  docs/Other SDL Features/Uploading Images/index.md
  docs/Speech and Audio/Playing Audio Indications/index.md
  docs/Speech and Audio/Playing Spoken Feedback/index.md
  docs/Video Streaming for Navigation Apps/Audio Streaming/index.md
  docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
  docs/Video Streaming for Navigation Apps/Introduction/index.md
  docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: fixing content, platform-android, platform-javaEE, platform-javaSE

#347 Update iOS custom lock screen
  docs/Getting Started/Adding the Lock Screen/index.md
Labels: fixing content, platform-iOS

#355 Add Swift Package Manager installation details
  docs/Developer Tools/Configuring SDL Logging/index.md
  docs/Getting Started/Installation/index.md
Labels: adding content, platform-iOS

#359 Note that Apple System Log Target is now deprecated
  docs/Developer Tools/Configuring SDL Logging/index.md
Labels: fixing content, platform-iOS

#363 Remove references to iOS 9
  docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
Labels: fixing content, platform-iOS

#346 Update code blocks in documentation
  docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
  docs/Developer Tools/Configuring SDL Logging/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Slider/index.md
  docs/Displaying a User Interface/Template Custom Buttons/index.md
  docs/Displaying a User Interface/Template Subscription Buttons/index.md
  docs/Getting Started/Adapting to the Head Unit Language/index.md
  docs/Getting Started/Adding the Lock Screen/index.md
  docs/Getting Started/Checking Supported Features/index.md
  docs/Getting Started/Integration Basics/index.md
  docs/Getting Started/Understanding Permissions/index.md
  docs/Other SDL Features/Batch Sending RPCs/index.md
  docs/Other SDL Features/Calling a Phone Number/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Getting the Navigation Destination/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Setting the Navigation Destination/index.md
  docs/Other SDL Features/Uploading Files/index.md
  docs/Other SDL Features/Uploading Images/index.md
  docs/Other SDL Features/Using App Services/index.md
  docs/Speech and Audio/Getting Microphone Audio/index.md
  docs/Speech and Audio/Playing Audio Indications/index.md
  docs/Speech and Audio/Playing Spoken Feedback/index.md
  docs/Video Streaming for Navigation Apps/Audio Streaming/index.md
  docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
  docs/Video Streaming for Navigation Apps/Touch Input/index.md
Labels: fixing content, platform-iOS

#379 Fix broken links
  docs/Customizing Look and Functionality/Customizing the Keyboard/index.md
  docs/Displaying a User Interface/Main Menu/index.md
  docs/Migrating to Newer SDL Versions/Updating to v4.9/index.md
  docs/Video Streaming for Navigation Apps/Introduction/index.md
Labels: fixing content

#367 Nav service route cancel
  docs/Video Streaming for Navigation Apps/Introduction/index.md
Labels: adding content, platform-android, platform-iOS
