Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2020-01, with the labels that each got.

#199 Fixed spelling, grammar and capitalization
  README.md
  docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
  docs/Developer Tools/Configuring SDL Logging/index.md
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Media Clock/index.md
  docs/Frequently Asked Questions/React Native/index.md
  docs/Getting Started/Adding the Lock Screen/index.md
  docs/Getting Started/Connecting to an Infotainment System/index.md
  docs/Getting Started/Example Apps/index.md
  docs/Getting Started/Integration Basics/index.md
  docs/Getting Started/SDK Configuration/index.md
  docs/Getting Started/Setting Security Level for Multiplexing/index.md
  docs/Getting Started/Understanding Permissions/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Uploading Files/index.md
  docs/Speech and Audio/Getting Microphone Audio/index.md
  docs/Speech and Audio/Playing Spoken Feedback/index.md
  docs/Video Streaming for Navigation Apps/Audio Streaming/index.md
  docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#201 Updated the logging to file section
  docs/Developer Tools/Configuring SDL Logging/index.md
Labels: adding content, fixing content, platform-iOS

#204 Add info about UI rotation while streaming
  docs/Video Streaming for Navigation Apps/Video Streaming/index.md
Labels: adding content, platform-iOS

#208 Choice Set image update
  docs/Displaying a User Interface/Popup Menus/assets/Generic_popup_menu_row.png
  docs/Displaying a User Interface/Popup Menus/assets/SYNC3_popup_menu_row.jpg
  docs/Displaying a User Interface/Popup Menus/assets/SYNC3_popup_menu_with_search.jpg
  docs/Displaying a User Interface/Popup Menus/index.md
Labels: fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#187 Added information about the RPC spec version
  config.json
  docs/Getting Started/Checking Supported Features/index.md
  docs/Getting Started/Connecting to an Infotainment System/assets/Generic_apps_screen.png
  docs/Getting Started/Connecting to an Infotainment System/assets/Generic_non_media.png
  docs/Getting Started/Connecting to an Infotainment System/assets/Manticore_cloud_embedded_app_settings.png
  docs/Getting Started/Connecting to an Infotainment System/assets/hmi1.png
  docs/Getting Started/Connecting to an Infotainment System/assets/hmi2.png
  docs/Getting Started/Connecting to an Infotainment System/assets/manticore1.png
  docs/Getting Started/Connecting to an Infotainment System/index.md
  docs/Getting Started/Example Apps/index.md
Labels: adding content, fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE
