Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2021-03, with the labels that each got.

#397 Fixed iOS Using App Services code update
  docs/Other SDL Features/Using App Services/index.md
Labels: fixing content, platform-iOS

#396 0238 Keyboard Enhancements Documentation Updates
  docs/Displaying a User Interface/Popup Keyboards/assets/SYNC3_keyboard_search.bmp
  docs/Displaying a User Interface/Popup Keyboards/assets/keyboard_numeric.png
  docs/Displaying a User Interface/Popup Keyboards/assets/keyboard_numeric_masked.png
  docs/Displaying a User Interface/Popup Keyboards/assets/keyboard_querty_custom_keys.png
  docs/Displaying a User Interface/Popup Keyboards/assets/keyboard_search.png
  docs/Displaying a User Interface/Popup Keyboards/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE

#401 Added documentation for Media Skip Indicators
  docs/Displaying a User Interface/Media Clock/assets/generic_sdlSeekStreamingIndicatorType_Time.png
  docs/Displaying a User Interface/Media Clock/index.md
  docs/Displaying a User Interface/Template Subscription Buttons/index.md
Labels: adding content, platform-iOS

#407 Added documentation for Main Menu UI Updates
  docs/Displaying a User Interface/Main Menu/assets/Generic_grid_layout_dark.png
  docs/Displaying a User Interface/Main Menu/assets/Generic_list_layout_dark.png
  docs/Displaying a User Interface/Main Menu/assets/Generic_menu_dark.png
  docs/Displaying a User Interface/Main Menu/index.md
Labels: adding content, platform-android, platform-iOS

#418 Add overwrite usage to JS docs
  docs/Other SDL Features/Uploading Files/index.md
Labels: fixing content, platform alignment, platform-javascript

#320 Fix typo in setting night color scheme
  docs/Customizing Look and Functionality/Customizing the Template/index.md
Labels: fixing content, platform-android, platform-javaEE, platform-javaSE

#427 Remove accio installation from the guides
  docs/Getting Started/Installation/index.md
Labels: fixing content, platform-iOS
