Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2021-05, with the labels that each got.

#442 Added instructions on how to clear voice commands
  docs/Speech and Audio/Setting Up Voice Commands/index.md
Labels: adding content, fixing content, platform-android, platform-iOS, platform-javaEE, platform-javaSE, platform-javascript

#447 Add information about Xcode 12.5 canBecomeFocused change
  docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
Labels: fixing content, platform-iOS

#448 Added information about how empty voice command strings are handled
  docs/Speech and Audio/Setting Up Voice Commands/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE, platform-javascript
