Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2021-06, with the labels that each got.

#453 Add Code Tabs to iOS Code
  config.json
  docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
  docs/Customizing Look and Functionality/Customizing the Keyboard/index.md
  docs/Customizing Look and Functionality/Customizing the Template/index.md
  docs/Developer Tools/Configuring SDL Logging/index.md
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Alerts and Subtle Alerts/index.md
  docs/Displaying a User Interface/Main Menu/index.md
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Media Clock/index.md
  docs/Displaying a User Interface/Popup Keyboards/index.md
  docs/Displaying a User Interface/Popup Menus/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Slider/index.md
  docs/Displaying a User Interface/Template Custom Buttons/index.md
  docs/Displaying a User Interface/Template Images/index.md
  docs/Displaying a User Interface/Template Subscription Buttons/index.md
  docs/Displaying a User Interface/Template Text/index.md
  docs/Frequently Asked Questions/React Native/index.md
  docs/Getting Started/Adapting to the Head Unit Language/index.md
  docs/Getting Started/Adding the Lock Screen/index.md
  docs/Getting Started/Checking Supported Features/index.md
  docs/Getting Started/Connecting to an Infotainment System/index.md
  docs/Getting Started/Installation/index.md
  docs/Getting Started/Integration Basics - iOS/index.md
  docs/Getting Started/Multiple Transports/index.md
  docs/Getting Started/SDK Configuration/index.md
  docs/Getting Started/Understanding Permissions/index.md
  docs/Migrating to Newer SDL iOS Versions/Updating to v4.3+/index.md
  docs/Migrating to Newer SDL iOS Versions/Updating to v5.0+/index.md
  docs/Other SDL Features/Batch Sending RPCs/index.md
  docs/Other SDL Features/Calling a Phone Number/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Creating an OEM Cloud App Store/index.md
  docs/Other SDL Features/Encryption/index.md
  docs/Other SDL Features/Getting the Navigation Destination/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Retrieving Vehicle Data/index.md
  docs/Other SDL Features/Setting the Navigation Destination/index.md
  docs/Other SDL Features/Uploading Files/index.md
  docs/Other SDL Features/Uploading Images/index.md
  docs/Other SDL Features/Using App Services/index.md
  docs/Speech and Audio/Getting Microphone Audio/index.md
  docs/Speech and Audio/Playing Audio Indications/index.md
  docs/Speech and Audio/Playing Spoken Feedback/index.md
  docs/Speech and Audio/Setting Up Voice Commands/index.md
  docs/Video Streaming for Navigation Apps/Audio Streaming/index.md
  docs/Video Streaming for Navigation Apps/Displaying Turn Directions/index.md
  docs/Video Streaming for Navigation Apps/Introduction/index.md
  docs/Video Streaming for Navigation Apps/Menus/index.md
  docs/Video Streaming for Navigation Apps/Supporting Haptic Input/index.md
  docs/Video Streaming for Navigation Apps/Touch Input/index.md
  docs/Video Streaming for Navigation Apps/Video Streaming - iOS/index.md
Labels: fixing content, platform-iOS

#455 Updated voice commands guide to include more information about duplicate strings
  docs/Speech and Audio/Setting Up Voice Commands/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE, platform-javascript

#463 Summer 2021 Guide Updates
  docs/Customizing Look and Functionality/Customizing Help Prompts/index.md
  docs/Customizing Look and Functionality/Customizing the Template/index.md
  docs/Displaying a User Interface/Adaptive Interface Capabilities/index.md
  docs/Displaying a User Interface/Alerts and Subtle Alerts/index.md
  docs/Displaying a User Interface/Main Screen Templates/index.md
  docs/Displaying a User Interface/Template Custom Buttons/index.md
  docs/Displaying a User Interface/Template Images/index.md
  docs/Getting Started/Adding the Lock Screen/index.md
  docs/Getting Started/Checking Supported Features/index.md
  docs/Getting Started/Example Apps/index.md
  docs/Getting Started/Installation/index.md
  docs/Getting Started/Understanding Permissions/index.md
  docs/Other SDL Features/Creating an App Service/index.md
  docs/Other SDL Features/Getting the Navigation Destination/index.md
  docs/Other SDL Features/Remote Control Vehicle Features/index.md
  docs/Other SDL Features/Uploading Files/index.md
  docs/Other SDL Features/Uploading Images/index.md
  docs/Other SDL Features/Using App Services/index.md
  docs/Speech and Audio/Playing Audio Indications/index.md
  docs/Speech and Audio/Setting Up Voice Commands/index.md
Labels: epic content update
