Repository smartdevicelink/sdl_app_library_guides, pull requests merged in 2021-04, with the labels that each got.

#415 Add JS ChoiceSetManager Documentation
  docs/Customizing Look and Functionality/Customizing the Keyboard/index.md
  docs/Displaying a User Interface/Popup Keyboards/index.md
  docs/Displaying a User Interface/Popup Menus/index.md
Labels: adding content, platform alignment, platform-javascript

#429 JS Broaden Choice Uniqueness
  docs/Displaying a User Interface/Popup Menus/index.md
Labels: platform alignment, platform-javascript

#413 Video streaming updates
  docs/Video Streaming for Navigation Apps/Video Streaming - Java/index.md
  docs/Video Streaming for Navigation Apps/Video Streaming - iOS/index.md
Labels: adding content, platform-android, platform-iOS

#403 Add Custom PlayRate Documentation
  docs/Displaying a User Interface/Media Clock/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE, platform-javascript

#420 Update guides with notes about the id ranges
  docs/Displaying a User Interface/Alerts and Subtle Alerts/index.md
  docs/Displaying a User Interface/Main Menu/index.md
  docs/Displaying a User Interface/Popup Keyboards/index.md
  docs/Displaying a User Interface/Popup Menus/index.md
  docs/Displaying a User Interface/Scrollable Message/index.md
  docs/Displaying a User Interface/Slider/index.md
  docs/Displaying a User Interface/Template Custom Buttons/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE, platform-javascript

#423 Artwork Overwriting with Screen Manager
  docs/Displaying a User Interface/Template Images/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE, platform-javascript

#431 AlertManager additions
  docs/Displaying a User Interface/Alerts and Subtle Alerts/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE, platform-javascript

#425 Implement SDL-0293 Guides - OEM Exclusive Apps
  docs/Getting Started/Integration Basics - JS/index.md
  docs/Getting Started/Integration Basics - Java/index.md
  docs/Getting Started/Integration Basics - iOS/index.md
Labels: adding content, platform-android, platform-iOS, platform-javaEE, platform-javaSE, platform-javascript
